# ベースイメージとしてnginxを使用
FROM nginx:alpine

# デフォルトの静的ファイルディレクトリを作成
RUN mkdir -p /usr/share/nginx/html

# カスタムnginx設定ファイルをコンテナ内にコピー
COPY nginx.conf /etc/nginx/nginx.conf

# Viteでビルドした静的ファイルをnginxのhtmlディレクトリにコピー
COPY ./bcrlweb/app/dist /usr/share/nginx/html

# nginxがデフォルトで80ポートで待ち受ける
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]