# --- ビルドフェーズ ---
    FROM node:20 AS build

    WORKDIR /app
    COPY ./app/package*.json ./
    RUN npm install
    
    COPY ./app .
    RUN npm run build
    
    # --- 配信フェーズ ---
    FROM nginx:alpine AS production
    
    # Nginx 設定ファイルを上書き
    COPY nginx.conf /etc/nginx/conf.d/default.conf
    
    # dist フォルダを公開ディレクトリにコピー
    COPY --from=build /app/dist /usr/share/nginx/html
    
    # 必要に応じてポート変更（デフォルト 80）
    EXPOSE 80
    
    CMD ["nginx", "-g", "daemon off;"]