services:
  bcrl:
    build:
      context: ./bcrl/.devcontainer
      dockerfile: "./Dockerfile"
    ports:
      - "4000:4000"
    volumes:
      - ..:/bcrl
      - shared:/shared/bcrlapi/json
    command: sleep infinity
  fastapi:
    build:
      context: ./fastapi
      dockerfile: "./Dockerfile"
    ports:
      - "4001:80"
    volumes:
      - ./fastapi:/fastapi
      - shared:/shared/bcrlapi/json
  # web:
  #   image: nginx:latest
  #   ports:
  #     - "4002:80"
  #   volumes:
  #     - ./html:/usr/share/nginx/html
  #   networks:
  #     - mynetwork
  # MOC
  app:
  client:
volumes:
  shared:

