services:
  bcrlapp:
    profiles: ["production"]
    build:
      context: ./bcrlapp
    ports:
      - "4000:4000"
    volumes:
      - ./bcrlapp:/bcrlapp
      - shared:/shared
    command: python -u /bcrlapp/status_monitor.py 30

  bcrlapi:
    profiles: ["production" , "dev", "test"] 
    build:
      context: ./bcrlapi
    ports:
      - "4001:80"
    volumes:
      - ./bcrlapi:/bcrlapi
      - ./bcrlapi:/bcrlapi
      - shared:/shared
    entrypoint: [ "/bcrlapi/entrypoint.sh" ]
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    working_dir: /bcrlapi

  bcrlweb_dev:
    profiles: ["dev"]
    build:
      context: ./bcrlweb
      dockerfile: Dockerfile.dev
    ports:
      - "4002:5173"
    volumes:
      - ./bcrlweb/app:/app
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173

  bcrlweb_production:
    profiles: ["production"]
    build:
      context: ./bcrlweb
      dockerfile: Dockerfile.production
    ports:
      - "4003:80"

  bcrlmock:
    profiles: ["dev", "test"] #bcrlappができたらproductionは消す
    build:
      context: ./bcrlmock
    ports:
      - "4004:80"
    volumes:
      - ./bcrlmock:/bcrlmock
      - shared:/shared
    command: python -u /bcrlmock/app/status_monitor.py 30

  clientmock:
    profiles: ["test"]
    build:
      context: ./clientmock
    ports:
      - "4005:80"
    command: sleep infinity
    volumes:
      - ./clientmock:/clientmock

volumes:
  shared:
