services:
  bcrl:
    profiles: ["Production"]
    build:
      context: ./bcrl/.devcontainer
    ports:
      - "4000:4000"
    volumes:
      - ./bcrl:/bcrl
      - shared:/shared
    command: sleep infinity

  fastapi:
    profiles: ["Production" , "dev", "test"] 
    build:
      context: ./fastapi
    ports:
      - "4001:80"
    volumes:
      - ./fastapi:/fastapi
      - shared:/shared
    entrypoint: [ "/fastapi/entrypoint.sh" ]
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    working_dir: /fastapi

  bcrlweb:
    profiles: ["Production", "dev"]
    build:
      context: ./bcrlweb
    ports:
      - "4002:5173"
    volumes:
      - ./bcrlweb/app:/app
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173

  # nginx:
  #   profiles: ["Production", "dev"]
  #   build:
  #     context: ./bcrlweb
  #   ports:
  #     - "4003:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - shared:/shared
  #   depends_on:
  #     - fastapi
  #     - bcrlweb

  bcrlmock:
    profiles: ["dev", "test"]
    build:
      context: ./bcrlmock
    ports:
      - "4004:80"
    volumes:
      - ./bcrlmock:/bcrlmock
      - shared:/shared
    command: python -u /bcrlmock/app/status_monitor.py 30

  clientmock:
    profiles: ["test"]
    build:
      context: ./clientmock
    ports:
      - "4005:80"
    command: sleep infinity
    volumes:
      - ./clientmock:/clientmock

volumes:
  shared:
