services:
  bcrl:
    profiles: ["dev"]
    build:
      context: ./bcrl/.devcontainer
    ports:
      - "4000:4000"
    volumes:
      - ./bcrl:/bcrl
      - shared:/shared
    command: sleep infinity

  fastapi:
    profiles: ["mock"]
    build:
      context: ./fastapi
    ports:
      - "4001:80"
    volumes:
      - ./fastapi:/fastapi
      - shared:/shared
    entrypoint: [ "/fastapi/entrypoint.sh" ]
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    working_dir: /fastapi

  bcrlweb:
    profiles: ["mock"]
    build:
      context: ./bcrlweb
    ports:
      - "4002:5173"
    volumes:
      - ./bcrlweb/app:/app
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173

  bcrlmock:
    profiles: ["mock"]
    build:
      context: ./bcrlmock
    ports:
      - "4003:80"
    volumes:
      - ./bcrlmock:/bcrlmock
      - shared:/shared
    command: python -u /bcrlmock/app/status_monitor.py 30

  clientmock:
    profiles: ["mock"]
    build:
      context: ./clientmock
    ports:
      - "4004:80"
    command: sleep infinity
    volumes:
      - ./clientmock:/clientmock

volumes:
  shared:
